server:
  port: 8080
  context-path: /seed
spring:
  application:
    name: seed
  profiles:
    active: pro
  # druid配置
  druid:
   driver-class-name: com.mysql.jdbc.Driver
   initial-size: 5
   min-idle: 5
   max-active: 20
   max-wait: 60000
   validation-query: select 1
   time-between-eviction-runs-millis: 60000
   test-on-borrow: false
   test-while-idle: true
  mvc:
    throw-exception-if-no-handler-found: true
# Mybatis配置
mybatis:
  type-aliases-package: com.supan.vshare.model
  mapper-locations: classpath:mapper/*Mapper.xml
mapper:
  mappers:
    - com.supan.vshare.core.Mapper
  not-empty: true
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# 日志配置
logging:
  config: classpath:logback.xml
  path: C://opt/log/
#logging:
#    file: /opt/log/seed.log
#    config: classpath:logback.xml
#    level:
#      root: info
#      org.springframework: info
#      com.supan.vshare: debug
#      tk.mybatis: debug
#      org.apache.ibatis: debug
#    path: /opt/log/
#  swagger:
#    title: spring-boot-starter-swagger
#    description: Starter for swagger 3.x
#    version: 1.3.0.RELEASE
#    license: Apache License,Version 2.0
#    contact:
#      name: supan
#      url: http://gome.inc
#      email: gome.inc@gome.com.cn
#    base-package: com.gome
#    base-path: /**

